# setx OPENAI_API_KEY "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"

python WebInterface/server/webserver.py
